In [2]:
import numpy as np 
import gym
import random
import time
from IPython.display import clear_output

In [4]:
env = gym.make("FrozenLake-v0")

In [8]:
action_space_size = env.action_space.n
state_space_size = env.observation_space.n
q_table = np.zeros((state_space_size, action_space_size))
print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [10]:
num_episodes = 10000
max_steps_per_episode = 100

learning_rate = 0.1
discount_rate = 0.99

exploration_rate = 1
max_exploration_rate = 1
min_exploration_rate = 0.01
exploration_decay_rate = 0.01

In [11]:
rewards = list()
for episode in range(num_episodes):
    state = env.reset()
    
    done = False
    rewards_current_episode = 0
    
    for step in range(max_steps_per_episode):
        
        exploration_rate_threshold = random.uniform(0, 1)
        if exploration_rate_threshold > exploration_rate:
            action = np.argmax(q_table[state, :])
        else:
            action = env.action_space.sample()
            
        new_state, reward, done, info = env.step(action)
        
        q_table[state, action] = q_table[state, action] * (1 - learning_rate) + learning_rate * \
        (reward + discount_rate * np.max(q_table[new_state, :]))
        
        state = new_state
        rewards_current_episode += reward
        
        if done == True:
            break
            
    exploration_rate = min_exploration_rate + (max_exploration_rate - min_exploration_rate) * \
    np.exp(-exploration_decay_rate*episode)
    
    rewards.append(rewards_current_episode)
    

In [12]:
q_table

array([[0.52787395, 0.49592762, 0.48501746, 0.50081861],
       [0.15603741, 0.23406153, 0.23057403, 0.41688292],
       [0.32627885, 0.19657216, 0.2035293 , 0.22697175],
       [0.18023288, 0.0052048 , 0.00728306, 0.00716077],
       [0.54510141, 0.28564898, 0.20575096, 0.30731431],
       [0.        , 0.        , 0.        , 0.        ],
       [0.35879262, 0.19989484, 0.15722425, 0.05578831],
       [0.        , 0.        , 0.        , 0.        ],
       [0.46040399, 0.37630924, 0.39149021, 0.59606846],
       [0.47294569, 0.65322493, 0.32008162, 0.44962212],
       [0.62103344, 0.35945654, 0.40672122, 0.32646435],
       [0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        ],
       [0.57653621, 0.52629349, 0.75443415, 0.49149628],
       [0.75778202, 0.86225806, 0.79095519, 0.69741577],
       [0.        , 0.        , 0.        , 0.        ]])

In [22]:
def chunks(l, n):
    # For item i in a range that is a length of l,
    for i in range(0, len(l), n):
        # Create an index range for l of n items:
        yield l[i:i+n]

In [23]:
np.mean(list(chunks(rewards, 1000)), axis=1)

array([0.114, 0.189, 0.194, 0.465, 0.698, 0.709, 0.636, 0.676, 0.674,
       0.692])

In [25]:
num_episode_test = 4

for episode in range(num_episode_test):
    state = env.reset()
    
    done = False
    time.sleep(1)
    for step in range(max_steps_per_episode):
        clear_output(wait=True)
        env.render()
        time.sleep(0.3)

        action = np.argmax(q_table[state, :])
        new_state, reward, done, info = env.step(action)
        
        state = new_state
        
        if done == True:
            break

  (Right)
SFFF
FHFH
FFFH
HFFG


In [26]:
q_table

array([[0.52787395, 0.49592762, 0.48501746, 0.50081861],
       [0.15603741, 0.23406153, 0.23057403, 0.41688292],
       [0.32627885, 0.19657216, 0.2035293 , 0.22697175],
       [0.18023288, 0.0052048 , 0.00728306, 0.00716077],
       [0.54510141, 0.28564898, 0.20575096, 0.30731431],
       [0.        , 0.        , 0.        , 0.        ],
       [0.35879262, 0.19989484, 0.15722425, 0.05578831],
       [0.        , 0.        , 0.        , 0.        ],
       [0.46040399, 0.37630924, 0.39149021, 0.59606846],
       [0.47294569, 0.65322493, 0.32008162, 0.44962212],
       [0.62103344, 0.35945654, 0.40672122, 0.32646435],
       [0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        ],
       [0.57653621, 0.52629349, 0.75443415, 0.49149628],
       [0.75778202, 0.86225806, 0.79095519, 0.69741577],
       [0.        , 0.        , 0.        , 0.        ]])